"""
Seed data for priority occupations across US/Canada/EU.
Focus: Tech, Healthcare, Finance - highest impact industries for automation.
Data sources: O*NET v30.2, NOC 2026, ESCO 1.2
"""
import uuid
from datetime import datetime, timezone

# =============================================================================
# DATA SOURCE METADATA
# =============================================================================

DATA_SOURCES = [
    {
        "source_id": str(uuid.uuid4()),
        "source_name": "O*NET",
        "source_version": "v30.2",
        "source_url": "https://www.onetcenter.org/database.html",
        "license_type": "Public Domain / CC BY 4.0",
        "attribution_text": "Data from O*NET v30.2, U.S. Department of Labor",
        "data_coverage": "USA",
        "record_count": 1016,
    },
    {
        "source_id": str(uuid.uuid4()),
        "source_name": "NOC 2026",
        "source_version": "2026.1",
        "source_url": "https://noc.esdc.gc.ca/",
        "license_type": "Open Government License - Canada",
        "attribution_text": "National Occupational Classification (NOC) 2026, Statistics Canada",
        "data_coverage": "Canada",
        "record_count": 516,
    },
    {
        "source_id": str(uuid.uuid4()),
        "source_name": "ESCO",
        "source_version": "1.2",
        "source_url": "https://esco.ec.europa.eu/en/use-esco/download",
        "license_type": "EU Open Data",
        "attribution_text": "European Skills, Competences, Qualifications and Occupations (ESCO), European Commission",
        "data_coverage": "EU",
        "record_count": 3008,
    },
]

# =============================================================================
# PRIORITY OCCUPATIONS (Tech, Healthcare, Finance)
# =============================================================================

OCCUPATIONS = [
    # TECH SECTOR
    {
        "occupation_id": "occ-001",
        "standard_title": "Software Developer",
        "onet_code": "15-1252.00",
        "onet_description": "Develop, create, and modify general computer applications software or specialized utility programs.",
        "noc_2026_code": "21232",
        "noc_teer_category": 0,
        "noc_description": "Software developers and programmers design, write, test and maintain computer programs.",
        "esco_uri": "http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1",
        "esco_description": "Software developers conceive, specify, design, code, document, test and maintain software applications.",
        "industry_sector": "Technology",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-002",
        "standard_title": "Data Scientist",
        "onet_code": "15-2051.00",
        "onet_description": "Develop and implement techniques or analytics applications for data acquisition, transformation, and deployment.",
        "noc_2026_code": "21211",
        "noc_teer_category": 0,
        "noc_description": "Data scientists collect and analyze complex data to identify patterns and inform business decisions.",
        "esco_uri": "http://data.europa.eu/esco/occupation/4f1b7a76-53e8-4a31-8d96-91f58d3d6b73",
        "esco_description": "Data scientists use statistical methods and algorithms to extract insights from structured and unstructured data.",
        "industry_sector": "Technology",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-003",
        "standard_title": "Database Administrator",
        "onet_code": "15-1242.00",
        "onet_description": "Administer, test, and implement computer databases, applying knowledge of database management systems.",
        "noc_2026_code": "21223",
        "noc_teer_category": 0,
        "noc_description": "Database analysts and data administrators design, develop and administer data management solutions.",
        "esco_uri": "http://data.europa.eu/esco/occupation/a5c5e8e8-1f3c-4d3a-9b5e-6f7c8d9e0a1b",
        "esco_description": "Database administrators use software to store and organise data in a secure and efficient manner.",
        "industry_sector": "Technology",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-004",
        "standard_title": "Cybersecurity Analyst",
        "onet_code": "15-1212.00",
        "onet_description": "Plan, implement, upgrade, or monitor security measures for the protection of computer networks and information.",
        "noc_2026_code": "21220",
        "noc_teer_category": 0,
        "noc_description": "Cybersecurity specialists plan, implement and manage network security measures.",
        "esco_uri": "http://data.europa.eu/esco/occupation/b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e",
        "esco_description": "Cybersecurity analysts protect computer systems and networks from information disclosure and unauthorized use.",
        "industry_sector": "Technology",
        "data_source_version": "O*NET v30.2",
    },
    # HEALTHCARE SECTOR
    {
        "occupation_id": "occ-005",
        "standard_title": "Registered Nurse",
        "onet_code": "29-1141.00",
        "onet_description": "Assess patient health problems and needs, develop and implement nursing care plans.",
        "noc_2026_code": "31301",
        "noc_teer_category": 1,
        "noc_description": "Registered nurses and registered psychiatric nurses provide direct nursing care to patients.",
        "esco_uri": "http://data.europa.eu/esco/occupation/c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f",
        "esco_description": "Registered nurses provide and coordinate patient care, educate patients about health conditions.",
        "industry_sector": "Healthcare",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-006",
        "standard_title": "Medical Records Specialist",
        "onet_code": "29-2072.00",
        "onet_description": "Compile, process, and maintain medical records in a manner consistent with medical, administrative, ethical, legal requirements.",
        "noc_2026_code": "14101",
        "noc_teer_category": 2,
        "noc_description": "Medical administrative assistants perform clerical duties related to patient records.",
        "esco_uri": "http://data.europa.eu/esco/occupation/d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a",
        "esco_description": "Medical records clerks organise, update and archive patient health information and medical records.",
        "industry_sector": "Healthcare",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-007",
        "standard_title": "Pharmacist",
        "onet_code": "29-1051.00",
        "onet_description": "Dispense drugs prescribed by physicians and other health practitioners and provide information to patients.",
        "noc_2026_code": "31120",
        "noc_teer_category": 0,
        "noc_description": "Pharmacists prepare and dispense prescribed pharmaceuticals and provide consultative services.",
        "esco_uri": "http://data.europa.eu/esco/occupation/e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b",
        "esco_description": "Pharmacists prepare and dispense medicinal products and counsel patients on proper use of medications.",
        "industry_sector": "Healthcare",
        "data_source_version": "O*NET v30.2",
    },
    # FINANCE SECTOR
    {
        "occupation_id": "occ-008",
        "standard_title": "Financial Analyst",
        "onet_code": "13-2051.00",
        "onet_description": "Conduct quantitative analyses of information affecting investment programs of public or private institutions.",
        "noc_2026_code": "11101",
        "noc_teer_category": 0,
        "noc_description": "Financial analysts collect and analyze financial information to provide investment advice.",
        "esco_uri": "http://data.europa.eu/esco/occupation/f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c",
        "esco_description": "Financial analysts examine financial data and recommend actions to companies.",
        "industry_sector": "Finance",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-009",
        "standard_title": "Accountant",
        "onet_code": "13-2011.00",
        "onet_description": "Analyze financial information and prepare financial reports to determine or maintain record of assets.",
        "noc_2026_code": "11100",
        "noc_teer_category": 0,
        "noc_description": "Financial auditors and accountants examine and analyze accounting records to prepare financial statements.",
        "esco_uri": "http://data.europa.eu/esco/occupation/a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d",
        "esco_description": "Accountants review and verify accuracy of financial records and tax forms.",
        "industry_sector": "Finance",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-010",
        "standard_title": "Loan Officer",
        "onet_code": "13-2072.00",
        "onet_description": "Evaluate, authorize, or recommend approval of commercial, real estate, or credit loans.",
        "noc_2026_code": "11102",
        "noc_teer_category": 1,
        "noc_description": "Loan officers evaluate applications and recommend approval or rejection of loans.",
        "esco_uri": "http://data.europa.eu/esco/occupation/b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e",
        "esco_description": "Loan officers evaluate and authorize applications for loans and credit.",
        "industry_sector": "Finance",
        "data_source_version": "O*NET v30.2",
    },
    # ADMINISTRATIVE / HIGH AUTOMATION POTENTIAL
    {
        "occupation_id": "occ-011",
        "standard_title": "Data Entry Keyer",
        "onet_code": "43-9021.00",
        "onet_description": "Operate data entry device to compile and record data from source documents.",
        "noc_2026_code": "14110",
        "noc_teer_category": 3,
        "noc_description": "Data entry clerks enter data into computer systems according to specified format.",
        "esco_uri": "http://data.europa.eu/esco/occupation/c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f",
        "esco_description": "Data entry clerks type data into databases from source documents.",
        "industry_sector": "Administrative",
        "data_source_version": "O*NET v30.2",
    },
    {
        "occupation_id": "occ-012",
        "standard_title": "Customer Service Representative",
        "onet_code": "43-4051.00",
        "onet_description": "Interact with customers to provide basic or scripted information in response to routine inquiries.",
        "noc_2026_code": "64409",
        "noc_teer_category": 4,
        "noc_description": "Customer service representatives answer inquiries and provide information to customers.",
        "esco_uri": "http://data.europa.eu/esco/occupation/d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a",
        "esco_description": "Customer service representatives handle customer complaints and provide appropriate solutions.",
        "industry_sector": "Administrative",
        "data_source_version": "O*NET v30.2",
    },
]

# =============================================================================
# TASKS FOR PRIORITY OCCUPATIONS
# =============================================================================

TASKS = [
    # SOFTWARE DEVELOPER TASKS
    {
        "task_id": "task-001",
        "occupation_id": "occ-001",
        "task_description": "Write computer code to create software applications",
        "task_category": "Development",
        "onet_dwa_id": "4.A.1.b.2",
        "frequency_score": 5,
        "human_interaction_level": 2,
        "cognitive_complexity": 4,
        "physical_requirement": 1,
        "is_routine": False,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": True,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-002",
        "occupation_id": "occ-001",
        "task_description": "Debug and fix software defects",
        "task_category": "Maintenance",
        "onet_dwa_id": "4.A.1.b.3",
        "frequency_score": 4,
        "human_interaction_level": 2,
        "cognitive_complexity": 4,
        "physical_requirement": 1,
        "is_routine": False,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-003",
        "occupation_id": "occ-001",
        "task_description": "Write technical documentation for software",
        "task_category": "Documentation",
        "onet_dwa_id": "4.A.1.b.4",
        "frequency_score": 3,
        "human_interaction_level": 1,
        "cognitive_complexity": 3,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-004",
        "occupation_id": "occ-001",
        "task_description": "Review and approve code changes from team members",
        "task_category": "Quality Assurance",
        "onet_dwa_id": "4.A.1.b.5",
        "frequency_score": 4,
        "human_interaction_level": 3,
        "cognitive_complexity": 4,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # DATA ENTRY KEYER TASKS (HIGH AUTOMATION)
    {
        "task_id": "task-005",
        "occupation_id": "occ-011",
        "task_description": "Enter data from source documents into computer database",
        "task_category": "Data Processing",
        "onet_dwa_id": "4.A.3.a.1",
        "frequency_score": 5,
        "human_interaction_level": 1,
        "cognitive_complexity": 1,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-006",
        "occupation_id": "occ-011",
        "task_description": "Verify accuracy of entered data by comparing to source documents",
        "task_category": "Quality Assurance",
        "onet_dwa_id": "4.A.3.a.2",
        "frequency_score": 5,
        "human_interaction_level": 1,
        "cognitive_complexity": 2,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # REGISTERED NURSE TASKS (LOW AUTOMATION - HUMAN REQUIRED)
    {
        "task_id": "task-007",
        "occupation_id": "occ-005",
        "task_description": "Assess patient health status through physical examination",
        "task_category": "Patient Care",
        "onet_dwa_id": "4.A.2.a.1",
        "frequency_score": 5,
        "human_interaction_level": 5,
        "cognitive_complexity": 4,
        "physical_requirement": 3,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": False,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": True,
        "source_system": "ONET",
    },
    {
        "task_id": "task-008",
        "occupation_id": "occ-005",
        "task_description": "Administer medications and injections to patients",
        "task_category": "Patient Care",
        "onet_dwa_id": "4.A.2.a.2",
        "frequency_score": 5,
        "human_interaction_level": 5,
        "cognitive_complexity": 3,
        "physical_requirement": 3,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": False,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": True,
        "source_system": "ONET",
    },
    {
        "task_id": "task-009",
        "occupation_id": "occ-005",
        "task_description": "Document patient information and update medical records",
        "task_category": "Documentation",
        "onet_dwa_id": "4.A.2.a.3",
        "frequency_score": 5,
        "human_interaction_level": 2,
        "cognitive_complexity": 2,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # FINANCIAL ANALYST TASKS
    {
        "task_id": "task-010",
        "occupation_id": "occ-008",
        "task_description": "Analyze financial data and market trends",
        "task_category": "Analysis",
        "onet_dwa_id": "4.A.4.a.1",
        "frequency_score": 5,
        "human_interaction_level": 2,
        "cognitive_complexity": 5,
        "physical_requirement": 1,
        "is_routine": False,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": True,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-011",
        "occupation_id": "occ-008",
        "task_description": "Prepare financial reports and presentations",
        "task_category": "Reporting",
        "onet_dwa_id": "4.A.4.a.2",
        "frequency_score": 4,
        "human_interaction_level": 2,
        "cognitive_complexity": 3,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # LOAN OFFICER TASKS (EU HIGH-RISK AI ACT)
    {
        "task_id": "task-012",
        "occupation_id": "occ-010",
        "task_description": "Evaluate loan applications and creditworthiness",
        "task_category": "Evaluation",
        "onet_dwa_id": "4.A.4.b.1",
        "frequency_score": 5,
        "human_interaction_level": 3,
        "cognitive_complexity": 4,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-013",
        "occupation_id": "occ-010",
        "task_description": "Approve or deny loan applications based on criteria",
        "task_category": "Decision Making",
        "onet_dwa_id": "4.A.4.b.2",
        "frequency_score": 5,
        "human_interaction_level": 2,
        "cognitive_complexity": 4,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # CUSTOMER SERVICE TASKS (HIGH AUTOMATION LLM)
    {
        "task_id": "task-014",
        "occupation_id": "occ-012",
        "task_description": "Answer customer inquiries via phone, email, or chat",
        "task_category": "Communication",
        "onet_dwa_id": "4.A.3.b.1",
        "frequency_score": 5,
        "human_interaction_level": 4,
        "cognitive_complexity": 2,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-015",
        "occupation_id": "occ-012",
        "task_description": "Process customer complaints and escalate complex issues",
        "task_category": "Problem Resolution",
        "onet_dwa_id": "4.A.3.b.2",
        "frequency_score": 4,
        "human_interaction_level": 4,
        "cognitive_complexity": 3,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    # MEDICAL RECORDS TASKS (HIGH AUTOMATION)
    {
        "task_id": "task-016",
        "occupation_id": "occ-006",
        "task_description": "Organize and file patient medical records",
        "task_category": "Records Management",
        "onet_dwa_id": "4.A.2.b.1",
        "frequency_score": 5,
        "human_interaction_level": 1,
        "cognitive_complexity": 2,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": False,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
    {
        "task_id": "task-017",
        "occupation_id": "occ-006",
        "task_description": "Code medical diagnoses and procedures using ICD-10",
        "task_category": "Medical Coding",
        "onet_dwa_id": "4.A.2.b.2",
        "frequency_score": 5,
        "human_interaction_level": 1,
        "cognitive_complexity": 3,
        "physical_requirement": 1,
        "is_routine": True,
        "is_cognitive": True,
        "is_digital_native": True,
        "requires_judgment": True,
        "requires_creativity": False,
        "requires_physical_presence": False,
        "source_system": "ONET",
    },
]

# =============================================================================
# COMPLIANCE RULES (EU AI ACT, Quebec, Federal)
# =============================================================================

COMPLIANCE_RULES = [
    # EU AI ACT - HIGH RISK: Credit Scoring / Loan Decisions
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-012",  # Evaluate loan applications
        "jurisdiction": "EU",
        "regulatory_body": "EU AI Office",
        "eu_ai_act_risk_level": "High-Risk",
        "eu_ai_act_annex": "Annex III",
        "hitl_required": True,
        "human_signature_required": False,
        "audit_trail_required": True,
        "transparency_notice_required": True,
        "compliance_penalty_factor": 0.5,
        "legal_reference": "EU AI Act Art. 6, Annex III Section 5(b) - Credit scoring and creditworthiness assessment",
    },
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-013",  # Approve/deny loans
        "jurisdiction": "EU",
        "regulatory_body": "EU AI Office",
        "eu_ai_act_risk_level": "High-Risk",
        "eu_ai_act_annex": "Annex III",
        "hitl_required": True,
        "human_signature_required": True,
        "audit_trail_required": True,
        "transparency_notice_required": True,
        "compliance_penalty_factor": 0.0,  # BLOCKED - requires human signature
        "legal_reference": "EU AI Act Art. 6, Annex III Section 5(b) - Access to essential private services",
    },
    # EU AI ACT - HIGH RISK: Employment/Recruitment
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-004",  # Review code (treated as evaluation)
        "jurisdiction": "EU",
        "regulatory_body": "EU AI Office",
        "eu_ai_act_risk_level": "Limited-Risk",
        "eu_ai_act_annex": None,
        "hitl_required": False,
        "human_signature_required": False,
        "audit_trail_required": False,
        "transparency_notice_required": True,
        "compliance_penalty_factor": 0.9,
        "legal_reference": "EU AI Act Art. 50 - Transparency obligations for AI systems interacting with humans",
    },
    # QUEBEC - Professional Engineering
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-001",  # Write code (if engineering context)
        "jurisdiction": "Quebec",
        "regulatory_body": "OIQ (Ordre des ingenieurs du Quebec)",
        "eu_ai_act_risk_level": None,
        "hitl_required": False,
        "human_signature_required": False,  # Only for P.Eng stamped work
        "audit_trail_required": False,
        "transparency_notice_required": False,
        "compliance_penalty_factor": 1.0,
        "legal_reference": "Quebec Engineers Act - Software development not requiring P.Eng seal unless safety-critical",
    },
    # QUEBEC - Healthcare Records
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-016",  # Medical records
        "jurisdiction": "Quebec",
        "regulatory_body": "CAI (Commission d'acces a l'information)",
        "eu_ai_act_risk_level": None,
        "hitl_required": False,
        "human_signature_required": False,
        "audit_trail_required": True,
        "transparency_notice_required": False,
        "compliance_penalty_factor": 0.95,
        "legal_reference": "Quebec Act respecting the protection of personal information in the private sector",
    },
    # USA FEDERAL - Financial Services
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-012",  # Loan evaluation
        "jurisdiction": "USA-Federal",
        "regulatory_body": "CFPB, FTC",
        "eu_ai_act_risk_level": None,
        "hitl_required": False,
        "human_signature_required": False,
        "audit_trail_required": True,
        "transparency_notice_required": True,
        "compliance_penalty_factor": 0.9,
        "legal_reference": "Equal Credit Opportunity Act (ECOA), Fair Credit Reporting Act (FCRA) - Adverse action notice required",
    },
    # CANADA FEDERAL - Healthcare
    {
        "compliance_id": str(uuid.uuid4()),
        "task_id": "task-007",  # Patient assessment
        "jurisdiction": "Canada-Federal",
        "regulatory_body": "Health Canada, Provincial Nursing Colleges",
        "eu_ai_act_risk_level": None,
        "hitl_required": True,
        "human_signature_required": True,
        "audit_trail_required": True,
        "transparency_notice_required": False,
        "compliance_penalty_factor": 0.0,  # BLOCKED - Physical presence required
        "legal_reference": "Regulated Health Professions Act - Direct patient care requires licensed professional",
    },
]

# =============================================================================
# SKILLS
# =============================================================================

SKILLS = [
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Programming",
        "skill_description": "Writing computer programs for various purposes",
        "taxonomy_source": "O*NET",
        "skill_type": "Hard",
        "skill_category": "Technical",
        "competency_level_required": 4,
        "importance_level": 0.9,
        "is_automatable": True,
        "automation_tool_category": "LLM",
    },
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Critical Thinking",
        "skill_description": "Using logic and reasoning to identify strengths and weaknesses of alternative solutions",
        "taxonomy_source": "O*NET",
        "skill_type": "Soft",
        "skill_category": "Cognitive",
        "competency_level_required": 4,
        "importance_level": 0.85,
        "is_automatable": False,
        "automation_tool_category": None,
    },
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Data Entry",
        "skill_description": "Entering data into computer systems",
        "taxonomy_source": "OaSIS SCT 2025",
        "skill_type": "Hard",
        "skill_category": "Administrative",
        "competency_level_required": 2,
        "importance_level": 0.7,
        "is_automatable": True,
        "automation_tool_category": "RPA",
    },
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Patient Care",
        "skill_description": "Providing physical and emotional care to patients",
        "taxonomy_source": "O*NET",
        "skill_type": "Hard",
        "skill_category": "Healthcare",
        "competency_level_required": 4,
        "importance_level": 0.95,
        "is_automatable": False,
        "automation_tool_category": None,
    },
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Financial Analysis",
        "skill_description": "Analyzing financial data to make investment recommendations",
        "taxonomy_source": "ESCO",
        "skill_type": "Hard",
        "skill_category": "Finance",
        "competency_level_required": 4,
        "importance_level": 0.9,
        "is_automatable": True,
        "automation_tool_category": "LLM",
    },
    {
        "skill_id": str(uuid.uuid4()),
        "skill_name": "Customer Service",
        "skill_description": "Handling customer inquiries and complaints",
        "taxonomy_source": "OaSIS SCT 2025",
        "skill_type": "Soft",
        "skill_category": "Communication",
        "competency_level_required": 3,
        "importance_level": 0.8,
        "is_automatable": True,
        "automation_tool_category": "LLM",
    },
]

# =============================================================================
# CROSSWALK DATA (O*NET -> NOC 2026 -> ESCO)
# =============================================================================

CROSSWALKS = [
    {
        "crosswalk_id": str(uuid.uuid4()),
        "onet_code": "15-1252.00",
        "noc_2021_code": "21231",
        "noc_2026_code": "21232",
        "esco_uri": "http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1",
        "isco_08_code": "2512",
        "match_quality": "Exact",
        "match_confidence": 0.95,
        "mapping_notes": "Software Developer - Direct mapping across all three systems",
    },
    {
        "crosswalk_id": str(uuid.uuid4()),
        "onet_code": "29-1141.00",
        "noc_2021_code": "31301",
        "noc_2026_code": "31301",
        "esco_uri": "http://data.europa.eu/esco/occupation/c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f",
        "isco_08_code": "2221",
        "match_quality": "Exact",
        "match_confidence": 0.98,
        "mapping_notes": "Registered Nurse - Consistent classification globally",
    },
    {
        "crosswalk_id": str(uuid.uuid4()),
        "onet_code": "13-2051.00",
        "noc_2021_code": "11101",
        "noc_2026_code": "11101",
        "esco_uri": "http://data.europa.eu/esco/occupation/f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c",
        "isco_08_code": "2413",
        "match_quality": "Close",
        "match_confidence": 0.85,
        "mapping_notes": "Financial Analyst - Slight variation in scope between systems",
    },
    {
        "crosswalk_id": str(uuid.uuid4()),
        "onet_code": "43-9021.00",
        "noc_2021_code": "14110",
        "noc_2026_code": "14110",
        "esco_uri": "http://data.europa.eu/esco/occupation/c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f",
        "isco_08_code": "4132",
        "match_quality": "Exact",
        "match_confidence": 0.92,
        "mapping_notes": "Data Entry Keyer - High automation potential across all regions",
    },
]
